import type { Metadata } from "next";
import 'bootstrap/dist/css/bootstrap.min.css'
import 'bootstrap-icons/font/bootstrap-icons.css'
import './globals.css'
import Sidebar from "./components/Sidebar";

export const metadata: Metadata = {
  title: "Teamtrack",
  description: "Generated by create next app"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body>
        <Sidebar/>
        <main className='main-section'>
        {children}
        </main>
        
      </body>
    </html>
  );
}
